# fly.toml app configuration file generated for crawl4ai-xj-dba on 2025-04-17T10:28:06Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'crawl4ai-xj-dba'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 11235
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[env]
  PORT = 11235

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
